@startuml

package ethanmmd.mastermind #91DF5C{}
package ethanmmd.mastermind.utils #91DF5C{}
package java.util{}
package java.io{}

ethanmmd.mastermind ..> ethanmmd.mastermind.utils
ethanmmd.mastermind ..> java.util
ethanmmd.mastermind.utils ..> java.io
@enduml