@startuml

package mastermind
package utils
package java.util
package java.io

[mastermind.jar] *--> mastermind
[mastermind.jar] *--> utils
[mastermind.jar] *--> java.util
[mastermind.jar] *--> java.io

@enduml